import '/tests/FeatureTests/Arguments.js';
import '/tests/FeatureTests/Array.js';
import '/tests/FeatureTests/ArrayBuffer.js';
import '/tests/FeatureTests/AsyncForm.js';
import '/tests/FeatureTests/AvoidStoringBuiltInSymbols.js';
import '/tests/FeatureTests/BigInt.js';
import '/tests/FeatureTests/BigInt64Array.js';
import '/tests/FeatureTests/BigUint64Array.js';
import '/tests/FeatureTests/Blob.js';
import '/tests/FeatureTests/Boolean.js';
import '/tests/FeatureTests/ConvertTo.js';
import '/tests/FeatureTests/Date.js';
import '/tests/FeatureTests/DecodingSymbolKeyWhenSymbolsNotSupported.js';
import '/tests/FeatureTests/Deduplication.js';
import '/tests/FeatureTests/DeferredTypeAttachedToDeferredType.js';
import '/tests/FeatureTests/DeferredTypeInsideKeyedCollection.js';
import '/tests/FeatureTests/Error.js';
import '/tests/FeatureTests/FallbackReferenceTracker.js';
import '/tests/FeatureTests/File.js';
import '/tests/FeatureTests/FileBlobFallback.js';
import '/tests/FeatureTests/Float32Array.js';
import '/tests/FeatureTests/Float64Array.js';
import '/tests/FeatureTests/Int16Array.js';
import '/tests/FeatureTests/Int32Array.js';
import '/tests/FeatureTests/Int8Array.js';
import '/tests/FeatureTests/MalformedEncodedData.js';
import '/tests/FeatureTests/Map.js';
import '/tests/FeatureTests/Null.js';
import '/tests/FeatureTests/Number.js';
import '/tests/FeatureTests/NumberCompression.js';
import '/tests/FeatureTests/Object.js';
import '/tests/FeatureTests/ObjectSymbolKeys.js';
import '/tests/FeatureTests/ObjectWrappedBoolean.js';
import '/tests/FeatureTests/ObjectWrappedNumber.js';
import '/tests/FeatureTests/ObjectWrappedString.js';
import '/tests/FeatureTests/OptionEncodeSymbolKeys.js';
import '/tests/FeatureTests/ReferentialDepth.js';
import '/tests/FeatureTests/Regex.js';
import '/tests/FeatureTests/Set.js';
import '/tests/FeatureTests/SharedArrayBuffer.js';
import '/tests/FeatureTests/String.js';
import '/tests/FeatureTests/Symbol.js';
import '/tests/FeatureTests/SymbolValuesOfBuiltInSymbols.js';
import '/tests/FeatureTests/Uint16Array.js';
import '/tests/FeatureTests/Uint32Array.js';
import '/tests/FeatureTests/Uint8Array.js';
import '/tests/FeatureTests/Uint8ClampedArray.js';
import '/tests/FeatureTests/Undefined.js';
import '/tests/FeatureTests/UnknownPointerKey.js';
import '/tests/FeatureTests/UnsupportedTypes.js';
import '/tests/FeatureTests/WeakMap.js';
import '/tests/FeatureTests/WeakSet.js';


// import jsonComplete from '/main.js';

// const encode = jsonComplete.encode;
// const decode = jsonComplete.decode;
